services:

    focalboard:
        image: mattermost/focalboard
        image: mattermost/focalboard:arm64
        container_name: focalboard    
        ports:
            - "4650:8000"
        restart: unless-stopped
