services:

    focalboard:
        image: mattermost/focalboard
        platform: linux/amd64
        container_name: focalboard    
        ports:
            - "4650:8000"
        restart: unless-stopped
